### ISSUE TITLE
Feature: 向仓库加入 Makefile 以便定义编译规则

### ISSUE THREAD

**Issue by GitHubonline1396529** [JohnsonLo00/lnumcmthesis#2]
# 问题描述

根据本仓库的文档所述，当使用 `bib` 文件来导入参考文献列表时，编译选项为：

XeLaTeX → BibTeX → XeLaTeX → XeLaTeX

当使用 thebibliography 环境来生成参考文献列表时，编译选项为

XeLaTeX → XeLaTeX → XeLaTeX

这种编译方式实际上是麻烦的。通常情况下我一般使用 GNU Make 命令编译文档。在定义好 Makefile 且计算机上安装配置过 GNU Make 之后（数学建模选手使用 Make 是常见的，通常来源于用户计算机上的 Mingw 环境，如 Git Bash 自带的 Mingw 或者大一学习 C 语言时安装的 GCC 工具集等）只需要使用简单的 `make` 命令即可快速编译文档。

# 建议

我创建了如下的 Makefile，支持自动检测 `refs.bib` 是否存在并调用不同的编译规则，并在编译结束之后自动清理 Auxiliary 文件。由于我使用的是 `bib`，在本地测试 `make` 命令后编译正确无误，然而 `thebibliography` 环境尚未被测试。（我的本地计算机上没有使用 `thebibliography` 的文档）

```makefile
# Makefile for compiling LaTeX document with or without bibtex

# Variables
TEXFILE = main.tex  # 主文件名
BIBFILE = refs.bib  # 参考文献文件名
PDFFILE = $(TEXFILE:.tex=.pdf)  # 最终生成的 PDF 文件名
AUXFILES = *.aux *.bbl *.blg *.log *.out *.toc *.loc *.soc # 临时文件

# 检查是否存在 .bib 文件
BIB_EXISTS := $(wildcard $(BIBFILE))

# 默认目标
all: $(PDFFILE)

# 编译主文件
$(PDFFILE): $(TEXFILE)
ifeq ($(BIB_EXISTS),)
	$(MAKE) pdf_nobib
else
	$(MAKE) pdf_bib
endif

# 编译规则（有 BibTeX）
pdf_bib:
	xelatex $(TEXFILE)
	bibtex $(basename $(TEXFILE))
	xelatex $(TEXFILE)
	xelatex $(TEXFILE)
	rm -rf $(AUXFILES)

# 编译规则（无 BibTeX）
pdf_nobib:
	xelatex $(TEXFILE)
	xelatex $(TEXFILE)
	xelatex $(TEXFILE)
	rm -rf $(AUXFILES)

# 清理临时文件
clean:
	rm -rf $(AUXFILES) $(PDFFILE)

clear:
	rm -rf $(AUXFILES)

# PHONY 目标，表示这些不是真实文件名
.PHONY: all clean clear pdf_bib pdf_nobib
```

我提议将 Makefile 加入仓库，以便用户能够轻易编译文档。

# 优势

- 易用性：用户可以使用单个命令（`make`）编译LaTeX文档。 
- 灵活性：Makefile 会自动检测 `.bib` 文件的存在，并相应地调整编译过程。 
- 更干净的项目：干净清晰的目标通过删除辅助文件来帮助维护一个整洁的项目目录。

# 请求

希望这份 Makefile 能够被合并进仓库，并在文档中有所提及。如有必要本人可以帮助编写文档及提交 Pull Request。感谢您浏览参阅本 Issue 并考虑我的建议。

**Comment by JohnsonLo00** [comment]
感谢关注lnumcmthesis.

个人认为，引入Makefile来提高tex文件编译效率**可以作为个别读者的高阶玩法**. 
* 使用Makefile的前提是**做好本地对 GNU make 的配置**. 而从非正规调研结果来看，由于 *“建模-编程-论文”* 这一 *老派分工规则* 的存在，参赛队中的 *论文手* 还是以 *Word玩家* 或者 *LaTeX轻量级玩家* 占多数，因此基于Makefile的操作对大部分人而言需要额外花费精力、不太友好.
* 多步编译虽为繁琐，但**属于“点按钮”式UI交互**，与基于命令行的交互相比，操作上还算简单明了.
* tex文件编译所产生的辅助文件，进行**针对性忽略或删除**即可，其中有两个还是有些作用的：
  - synctex文件：实现tex文件与pdf文件之间的跳转(即：前/反向搜索).
  - log文件：报错时可查看具体编译记录.
* 与Makefile相比，还可以考虑基于**latexmk**的操作.

综上，本人将考虑在下一版本的 `gbk_of_lnumcmthesis.pdf` 中**简单介绍**基于Makefile的编译操作，但**暂不考虑将其详细引入**. 望您理解，也欢迎继续关注lnumcmthesis以及名下其他repo的latex论文模板.

**Comment by GitHubonline1396529** [comment]
@JohnsonLo00 收到。非常感谢您的回复和建议。

1. 对于您有关 synctex 文件和 log 文件的建议，经修缮后的 Makefile 文件如下。尽管这份 Makefile 将不会被合并到代码的主分支，我认为通过将其保留在此 Issue 中可以便于其他模板使用者自行取用。
2. 感谢您提醒我有关基于 `latexmk` 定义编译规则的建议！之前忽略了这个。我会作进一步的考虑。

```makefile
# Makefile for compiling LaTeX document with or without bibtex

# Variables
TEXFILE = main.tex  # 主文件名
BIBFILE = refs.bib  # 参考文献文件名
PDFFILE = $(TEXFILE:.tex=.pdf)  # 最终生成的 PDF 文件名
AUXFILES = *.aux *.bbl *.blg *.out *.toc *.loc *.soc # 临时文件

# 检查是否存在 .bib 文件
BIB_EXISTS := $(wildcard $(BIBFILE))

# 默认目标
all: $(PDFFILE)

# 编译主文件
$(PDFFILE): $(TEXFILE)
ifeq ($(BIB_EXISTS),)
	$(MAKE) pdf_nobib
else
	$(MAKE) pdf_bib
endif

# 编译规则（有 BibTeX）
pdf_bib:
	xelatex $(TEXFILE)
	bibtex $(basename $(TEXFILE))
	xelatex $(TEXFILE)
	xelatex $(TEXFILE)
	latexmk -c

# 编译规则（无 BibTeX）
pdf_nobib:
	xelatex $(TEXFILE)
	xelatex $(TEXFILE)
	xelatex $(TEXFILE)
	latexmk -c

# 清理临时文件
clean:
	rm -rf $(AUXFILES) $(PDFFILE) *.log

clear:
	latexmk -c

# PHONY 目标，表示这些不是真实文件名
.PHONY: all clean clear pdf_bib pdf_nobib
```

本人目前处于 LaTeX 的学习阶段，其技不精，尚有诸项疏弊。得此交流学习，不胜其幸。
