### ISSUE TITLE
Feature: 是否考虑添置默认代码高亮方案

### ISSUE THREAD

**Issue by GitHubonline1396529** [JohnsonLo00/lnumcmthesis#3]
# 描述

我在使用 lnumcmthesis 模板时注意到模板在插入代码块的时候并无默认的代码高亮方案，所有的代码均以灰底黑字的样式直接插入。经查阅《全国大学生数学建模竞赛论文格式规范(2023年修订稿） 》，其中对于附录代码并无有关高亮颜色的具体要求。

在文件 [`lnumcmthesis.cls`](https://github.com/JohnsonLo00/lnumcmthesis/blob/main/lnumcmthesis.cls) 中有关代码环境的设置如下：

```tex
% --------------- 代码环境 --------------- %
\RequirePackage{verbatim} %简易代码环境（提供：verbatim 环境。缺点：不能解决断行问题。）
\RequirePackage{listings} %定制代码环境
\RequirePackage{matlab-prettifier} %MATLAB专门的代码环境
%代码环境定制
\lstset{
  basicstyle=\small\ttfamily, %整体的字号、字体
  stringstyle=\ttfamily, %字符串样式
  backgroundcolor=\color{gray!10}, %背景颜色
  frame=trbl, %显示各方向的代码框线条
  frameround=tttt, %设置代码框各棱角的形状
  breaklines=true, %自动断行
  showstringspaces=false, %取消特别的字符间距
  framexleftmargin=5pt, %内部左边距
}
% ======================================== %
```

# 提议

我认为可以考虑为模板设置默认的代码高亮样式，用一些基础的颜色覆盖关键字、字符串和注释。一个简单的 `\lstset` 配置如下所示：

```tex
% 代码环境定制
% 定义颜色
\definecolor{commentgreen}{HTML}{3CA53C}
% 设置代码环境
\lstset{
    basicstyle=\small\ttfamily, % 整体的字号、字体
    backgroundcolor=\color{gray!10}, % 背景颜色
    frame=trbl, %显示各方向的代码框线条
    frameround=tttt, % 设置代码框各棱角的形状
    showstringspaces=false, % 取消特别的字符间距
    framexleftmargin=5pt, % 内部左边距
    keywordstyle=\color{blue},
    commentstyle=\color{commentgreen},
    stringstyle=\color{red},
    numberstyle=\tiny\color{gray},
    stepnumber=1,
    numbersep=5pt,
    showspaces=false,
    showstringspaces=false,
    breaklines=true, % 自动断行
    % numberbychapter=true,
}
```

渲染效果截取部分代码如图所示：

![图片](https://github.com/user-attachments/assets/a0167eb1-cf0b-4769-94ac-4f1c6e65f13f)

# 优势

- 改进了代码的可读性和最终论文呈现的视觉效果
- 模板用户无需再对代码的高亮设计额外的方案
- 模板用户仍可以根据个人需要在 `main.tex` 中使用客制化的高亮方案覆盖现有方案，保障了模板的定制性

**Comment by JohnsonLo00** [comment]
本模板开发初期已考虑到该问题，采用的是**以加粗代替换色**的代码高亮方案(尽管加粗程度很不明显…)：
* 当对 `\lstinputlisting` 命令指定可选参数 `language=…` 时(即指定语言类型)，便会自动识别关键字进行高亮
* MATLAB有专门的IDE，有专门的高亮颜色标准，即直接使用 `style=Matlab-editor`
* 对于不同编辑器，**高亮颜色配置的标准不同**，故难以咬定一种合适的配色方案
* 在某些主流编辑器中，**关键字也按类型进行不同颜色高亮**(e.g. vscode)；然而`\lstset` 命令中的高亮设置会对所有关键字统一上色，这是另一种角度的配色标准不统一

当然，上述考虑过于细致，俨然可以如您所说直接指定颜色，比如我之前考虑到的一种配色方案(与所您给出的差不多). 因此，下一版本的开发会对代码高亮问题重新斟酌.

**Comment by GitHubonline1396529** [comment]
@JohnsonLo00 感谢您的回复。

对于默认的代码配色方案，我提议可以援引 Visual C++ 6.0 的配色设计。这个古早 IDE 有一些年头了，印象里其配色方案比较符合国内阅卷老师的习惯，而且也符合数模论文整体严谨的风格。

**Comment by JohnsonLo00** [comment]
本质上还是[红绿蓝]方案.
